spring:
  application:
    name: ms-websocket
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
    maxHttpPostSize: 4194304
    maxHttpHeaderSize: 65536
  maxHttpHeaderSize: 65536
  maxHttpPostSize: 4194304
  session:
    cookie:
      name: AuthorizationSessionId