spring:
  application:
    name: ms-websocket
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  port: 9005