server:
  port: 8768

spring:
  application:
    name: ms-gateway
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id:  websocket
          uri: lb:ws://ms-websocket
          predicates:
            - Path=/wsocket/**
          filters:
              - StripPrefix=1
        - id: demo
          uri: http://www.baidu.com
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  httpclient:
    enabled: false
  okhttp:
    enabled: true

logging:
  level:
    com.sailfish: debug