server:
  port: 8206
spring:
  application:
    name: nacos-sentinel-test
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel dashboard地址
        client-ip: 10.54.8.11
        port: 8719
      eager: true
management:
  endpoints:
    web:
      exposure:
        include: '*'